#!/usr/bin/env python3
"""
ReconSuite v2.0 — Full-Spectrum Reconnaissance Toolkit
CLI Interface with argparse, color output, proxy/Tor support.
All modules are self-contained and importable by the Flask dashboard.
"""

import argparse
import concurrent.futures
import json
import os
import re
import socket
import ssl
import sys
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

import dns.resolver
import requests
import whois
from bs4 import BeautifulSoup
from colorama import Fore, Style, init as colorama_init

# ── Globals ──────────────────────────────────────────────────────────
colorama_init(autoreset=True)
OUTPUT_DIR = Path("reports")
OUTPUT_DIR.mkdir(exist_ok=True)
SCREENSHOT_DIR = Path("screenshots")
SCREENSHOT_DIR.mkdir(exist_ok=True)

session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
})

# ── Proxy support ────────────────────────────────────────────────────
def configure_proxy(proxy_url: Optional[str] = None, use_tor: bool = False):
    if use_tor:
        proxy_url = "socks5://127.0.0.1:9050"
    if proxy_url:
        session.proxies = {"http": proxy_url, "https": proxy_url}
        if proxy_url.startswith("socks5"):
            try:
                import socks  # type: ignore
                socks.set_default_proxy(socks.SOCKS5, "127.0.0.1", 9050 if use_tor else 1080)
                socket.socket = socks.socksocket
            except ImportError:
                print(f"{Fore.YELLOW}[!] PySocks not installed, SOCKS proxy limited{Style.RESET_ALL}")

# ── Logging helpers ─────────────────────────────────────────────────
def log_info(msg: str): print(f"{Fore.CYAN}[*] {msg}{Style.RESET_ALL}")
def log_ok(msg: str): print(f"{Fore.GREEN}[+] {msg}{Style.RESET_ALL}")
def log_warn(msg: str): print(f"{Fore.YELLOW}[!] {msg}{Style.RESET_ALL}")
def log_err(msg: str): print(f"{Fore.RED}[-] {msg}{Style.RESET_ALL}")

def save_json(data, name: str, subdir: str = ""):
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = OUTPUT_DIR / subdir / f"{name}_{ts}.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, default=str)
    return str(path)

def save_markdown(data, name: str, subdir: str = ""):
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = OUTPUT_DIR / subdir / f"{name}_{ts}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(data)
    return str(path)

DISCLAIMER = (
    "\n---\n*This report was generated by ReconSuite v2.0 for authorised security assessment purposes only. "
    "Unauthorised use against targets you do not own or have explicit written permission to test is illegal. "
    "The authors assume no liability for misuse or damage caused by this tool.*\n"
)

# ═════════════════════════════════════════════════════════════════════
# MODULE 1: WHOIS Lookup
# ═════════════════════════════════════════════════════════════════════
def whois_lookup(domain: str) -> Dict:
    result = {"domain": domain, "error": None}
    try:
        w = whois.whois(domain)
        result.update({
            "registrar": w.registrar,
            "creation_date": str(w.creation_date) if w.creation_date else None,
            "expiration_date": str(w.expiration_date) if w.expiration_date else None,
            "name_servers": w.name_servers if w.name_servers else [],
            "org": w.org,
            "country": w.country,
            "emails": w.emails if w.emails else [],
            "status": w.status if w.status else [],
        })
    except Exception as e:
        result["error"] = str(e)
    return result

# ═════════════════════════════════════════════════════════════════════
# MODULE 2: DNS Enumeration
# ═════════════════════════════════════════════════════════════════════
def dns_enum(domain: str) -> Dict:
    records = {}
    for rtype in ["A", "AAAA", "MX", "NS", "TXT", "SOA", "CNAME"]:
        try:
            answers = dns.resolver.resolve(domain, rtype, lifetime=10)
            records[rtype] = [str(r) for r in answers]
        except Exception:
            records[rtype] = []
    return records

# ═════════════════════════════════════════════════════════════════════
# MODULE 3: Subdomain Enumeration
# ═════════════════════════════════════════════════════════════════════
SUBDOMAIN_WORDLIST = [
    "www", "mail", "ftp", "admin", "blog", "shop", "api", "dev", "test",
    "staging", "vpn", "remote", "webmail", "portal", "cpanel", "whm",
    "ns1", "ns2", "mx", "smtp", "pop3", "imap", "secure", "ssl",
    "login", "register", "app", "m", "mobile", "support", "help",
    "docs", "wiki", "forum", "community", "status", "cdn", "static",
    "assets", "img", "video", "files", "download", "upload", "backup",
    "db", "database", "sql", "mysql", "pg", "redis", "git", "jenkins",
    "jira", "confluence", "wiki", "svn", "dns", "ns2", "ns3", "ns4",
    "autodiscover", "owa", "exchange", "lyncdiscover", "sip",
    "meet", "chat", "web", "server", "node1", "node2", "cluster",
    "monitor", "grafana", "prometheus", "kibana", "elastic",
    "dashboard", "analytics", "tracking", "api-dev", "api-staging",
    "sandbox", "demo", "stage", "prod", "production", "dev2",
    "services", "service", "sso", "auth", "oauth", "idp",
    "images", "email", "newsletter", "partners", "careers", "jobs",
    "status", "health", "metrics", "logs", "audit", "connect",
    "my", "your", "account", "profile", "user", "users", "client",
    "clients", "customer", "customers", "billing", "payment",
    "pay", "checkout", "cart", "orders", "order", "store",
    "shop", "product", "products", "catalog", "category", "search",
    "beta", "alpha", "canary", "release", "release-1", "release-2",
    "patch", "hotfix", "bugfix", "fix", "experimental", "lab",
    "internal", "external", "public", "private", "corp", "office",
    "nyc", "lon", "sfo", "ams", "fra", "sin", "hkg", "nrt", "syd",
    "us", "eu", "asia", "americas", "emea", "apac", "latam",
    "storage", "object", "bucket", "s3", "blob", "data", "warehouse",
]

def subdomain_bruteforce(domain: str, wordlist: Optional[List[str]] = None) -> List[str]:
    found = []
    wl = wordlist or SUBDOMAIN_WORDLIST
    def _check(sub):
        fqdn = f"{sub}.{domain}"
        try:
            socket.getaddrinfo(fqdn, 80, socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
            return fqdn
        except (socket.gaierror, OSError):
            return None
    with concurrent.futures.ThreadPoolExecutor(max_workers=50) as ex:
        futures = {ex.submit(_check, sub): sub for sub in wl}
        for f in concurrent.futures.as_completed(futures):
            r = f.result()
            if r:
                found.append(r)
    return sorted(set(found))

def subdomain_crtsh(domain: str) -> List[str]:
    found = []
    try:
        resp = session.get(f"https://crt.sh/?q=%25.{domain}&output=json", timeout=30)
        if resp.status_code == 200:
            for e in resp.json():
                name = e.get("name_value", "")
                for n in name.split("\n"):
                    n = n.strip().lower()
                    if n and n.endswith(domain) and "*" not in n:
                        found.append(n)
    except Exception:
        pass
    return sorted(set(found))

def subdomain_enum(domain: str, brute: bool = True, passive: bool = True, progress_callback=None) -> Dict:
    result = {"domain": domain, "bruteforce": [], "passive": [], "all": []}
    total = (1 if brute else 0) + (1 if passive else 0)
    completed = [0]
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as ex:
        fb = ex.submit(subdomain_bruteforce, domain) if brute else None
        fc = ex.submit(subdomain_crtsh, domain) if passive else None
        if fb:
            try:
                result["bruteforce"] = fb.result(timeout=120)
            except Exception as e:
                log_warn(f"Brute-force subdomain scan error: {e}")
            completed[0] += 1
            if progress_callback:
                progress_callback(completed[0], total)
        if fc:
            try:
                result["passive"] = fc.result(timeout=60)
            except Exception as e:
                log_warn(f"crt.sh passive scan error: {e}")
            completed[0] += 1
            if progress_callback:
                progress_callback(completed[0], total)
    result["all"] = sorted(set(result["bruteforce"] + result["passive"]))
    return result

# ═════════════════════════════════════════════════════════════════════
# MODULE 4: Port Scanning
# ═════════════════════════════════════════════════════════════════════
TOP_PORTS = [
    21,22,23,25,53,80,81,110,111,123,135,139,143,161,179,389,
    443,445,465,500,514,515,543,544,548,554,587,631,636,646,
    873,990,993,995,1025,1026,1027,1028,1029,1110,1433,1434,
    1521,1604,1720,1723,1755,1900,2000,2001,2049,2103,2105,
    2107,2121,2401,2717,3000,3001,3128,3306,3389,3500,3521,
    4000,4001,4040,4045,4224,4242,4321,4443,4444,4500,4567,
    4662,4848,4899,5000,5001,5002,5004,5009,5050,5051,5060,
    5061,5101,5120,5190,5222,5223,5269,5432,5455,5500,5554,
    5555,5556,5600,5631,5632,5666,5672,5678,5800,5801,5802,
    5810,5900,5901,5902,5903,5984,5985,5986,6000,6001,6002,
    6082,6112,6129,6257,6346,6347,6379,6380,6481,6515,6522,
    6543,6665,6666,6667,6668,6669,6697,6789,6881,6882,6883,
    6884,6885,6886,6887,6888,6889,6890,6891,6892,6893,6894,
    6895,6896,6897,6898,6899,6900,6901,6969,7000,7001,7002,
    7004,7005,7007,7010,7025,7070,7100,7103,7106,7200,7201,
    7300,7301,7302,7306,7307,7310,7320,7322,7330,7340,7350,
    7360,7365,7380,7390,7391,7392,7393,7394,7395,7396,7397,
    7398,7399,7400,7401,7402,7443,7473,7474,7547,7548,7670,
    7674,7680,7689,7741,7777,7778,7779,7788,7789,7831,7878,
    7880,7900,7901,7902,7911,7995,8000,8001,8002,8005,8008,
    8009,8010,8020,8022,8031,8040,8050,8060,8070,8080,8081,
    8082,8085,8088,8090,8091,8092,8093,8095,8096,8097,8098,
    8099,8100,8101,8102,8111,8112,8123,8130,8131,8140,8161,
    8181,8182,8193,8194,8200,8222,8254,8291,8300,8310,8320,
    8351,8403,8411,8423,8443,8500,8501,8503,8554,8600,8610,
    8611,8612,8613,8614,8615,8649,8686,8733,8765,8766,8770,
    8778,8786,8787,8788,8790,8800,8873,8880,8881,8882,8883,
    8888,8889,8890,8891,8899,8983,9000,9001,9002,9003,9006,
    9009,9010,9011,9020,9021,9022,9025,9030,9040,9050,9060,
    9080,9090,9091,9092,9095,9099,9100,9101,9102,9103,9110,
    9120,9150,9151,9152,9180,9191,9200,9210,9220,9290,9300,
    9312,9320,9332,9344,9350,9351,9415,9418,9443,9485,9500,
    9502,9503,9535,9575,9593,9594,9595,9600,9612,9614,9616,
    9618,9620,9622,9624,9626,9628,9630,9632,9634,9636,9638,
    9640,9642,9644,9646,9648,9650,9660,9670,9680,9690,9700,
    9710,9720,9730,9740,9750,9760,9770,9780,9790,9800,9876,
    9877,9878,9898,9900,9981,9988,9990,9991,9992,9993,9994,
    9995,9996,9997,9998,9999,10000,10001,10002,10003,10004,
    10009,10010,10012,10024,10025,10082,10092,10100,10101,
    10102,10110,10113,10114,10115,10116,10117,10125,10160,
    10180,10200,10243,10566,10616,10617,10621,10626,10628,
    10629,10778,11110,11111,11967,12000,12174,12265,12345,
    13456,13722,13782,13783,14000,14238,14441,15000,15002,
    15003,15004,15660,15742,16000,16012,16016,16018,16080,
    16113,16992,16993,17877,18088,18201,18202,18203,18204,
    18205,18206,18207,18209,18210,18463,18634,18635,18636,
    18637,18638,18639,18640,18641,18642,18643,18644,18645,
    18646,18647,18648,18649,18650,18651,18652,18653,18654,
    18655,18656,18657,18658,18659,18660,18661,18662,18663,
    18664,18665,18666,18667,18668,18669,18670,18671,18672,
    18673,18674,18675,18676,18677,18678,18679,18680,18681,
    18682,18683,18684,18685,18686,18687,18688,18689,18690,
    18691,18692,18693,18694,18695,18696,18697,18698,18699,
    18700,18701,18702,18703,18704,18705,18706,18707,18708,
    18709,18710,18711,18712,18713,18714,18715,18716,18717,
    18718,18719,18720,18721,18722,18723,18724,18744,18745,
    18746,18747,18748,18749,18750,18751,18752,18769,18881,
    18988,19000,19101,19283,19315,19350,19780,19801,19842,
    20000,20005,20031,20221,20222,20828,21571,22939,23502,
    24444,24800,25734,25735,26214,27000,27352,27353,27355,
    27356,27715,28201,30000,30718,30951,31038,31337,32768,
    32769,32770,32771,32772,32773,32774,32775,32776,32777,
    32778,32779,32780,32781,32782,32783,32784,32785,33354,
    33899,34571,34572,34573,35500,38292,40193,40911,41511,
    44176,44442,44443,44501,45100,48080,49152,49153,49154,
    49155,49156,49157,49158,49159,49160,49161,49163,49165,
    49167,49175,49176,49400,49999,50000,50001,50002,50003,
    50006,50300,50389,50500,50636,50800,51103,51493,52673,
    52822,52848,52869,54045,54328,55055,55056,55555,55600,
    56737,56738,57294,57797,58080,60020,60443,61532,61900,
    62078,63331,64623,64680,65000,65129,65389
]

def scan_port(host: str, port: int, timeout: float = 1.5) -> Optional[int]:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            if s.connect_ex((host, port)) == 0:
                return port
    except Exception:
        pass
    return None

def port_scan(domain: str, ports: Optional[List[int]] = None, timeout: float = 1.5, progress_callback=None) -> Dict:
    target_ports = ports or TOP_PORTS
    result = {"host": domain, "open_ports": [], "total_scanned": len(target_ports)}
    def _scan_batch(port_list):
        return [p for p in port_list if scan_port(domain, p, timeout)]
    batch_size = 100
    batches = [target_ports[i:i+batch_size] for i in range(0, len(target_ports), batch_size)]
    completed = [0]
    total = len(batches)
    with concurrent.futures.ThreadPoolExecutor(max_workers=20) as ex:
        for f in concurrent.futures.as_completed([ex.submit(_scan_batch, b) for b in batches]):
            try:
                result["open_ports"].extend(f.result())
            except Exception:
                pass
            completed[0] += 1
            if progress_callback:
                progress_callback(completed[0], total)
    result["open_ports"] = sorted(set(result["open_ports"]))
    return result

# ═════════════════════════════════════════════════════════════════════
# MODULE 5: HTTP Headers + Security Audit
# ═════════════════════════════════════════════════════════════════════
SECURITY_HEADERS = {
    "Strict-Transport-Security": "HSTS missing — vulnerable to SSL stripping",
    "Content-Security-Policy": "CSP missing — vulnerable to XSS and data injection",
    "X-Content-Type-Options": "X-Content-Type-Options missing — MIME-sniffing risk",
    "X-Frame-Options": "X-Frame-Options missing — clickjacking risk",
    "X-XSS-Protection": "X-XSS-Protection header not set",
    "Referrer-Policy": "Referrer-Policy missing — information leakage risk",
    "Permissions-Policy": "Permissions-Policy missing — feature control not enforced",
    "Access-Control-Allow-Origin": "CORS not configured",
}

def check_http_headers(url: str) -> Dict:
    result = {"url": url, "status_code": None, "headers": {}, "issues": [], "score": 100}
    try:
        resp = session.get(url, timeout=15, allow_redirects=True)
        result["status_code"] = resp.status_code
        result["headers"] = dict(resp.headers)
        result["server"] = resp.headers.get("Server", "Unknown")
        result["powered_by"] = resp.headers.get("X-Powered-By", None)
        for hdr, warning in SECURITY_HEADERS.items():
            if hdr not in resp.headers:
                result["issues"].append({"header": hdr, "severity": "medium", "description": warning})
                result["score"] -= 12
        result["score"] = max(0, result["score"])
    except requests.RequestException as e:
        result["error"] = str(e)
    return result

# ═════════════════════════════════════════════════════════════════════
# MODULE 6: Tech Stack Fingerprinting
# ═════════════════════════════════════════════════════════════════════
TECH_SIGNATURES = {
    "jQuery": [r"jquery", r"jQuery"],
    "React": [r"react", r"React", r"__NEXT_DATA__", r"__NEXT_LOADED_PAGES__"],
    "Vue.js": [r"vue", r"Vue", r"__VUE__", r"vue-router"],
    "Angular": [r"angular", r"ng-", r"ng_version"],
    "Bootstrap": [r"bootstrap", r"Bootstrap"],
    "TailwindCSS": [r"tailwindcss", r"tailwind"],
    "WordPress": [r"/wp-content/", r"/wp-includes/", r"wp-json"],
    "Drupal": [r"Drupal", r"/sites/default/", r"drupal"],
    "Joomla": [r"joomla", r"Joomla"],
    "Laravel": [r"laravel", r"Laravel", r"_token"],
    "Django": [r"django", r"csrftoken", r"Django"],
    "Flask": [r"flask", r"Flask"],
    "Express": [r"express", r"Express", r"connect.sid"],
    "Ruby on Rails": [r"rails", r"Rails", r"_csrf_token"],
    "ASP.NET": [r"ASP\.NET", r"__VIEWSTATE", r"X-AspNet-Version"],
    "nginx": [r"nginx"],
    "Apache": [r"Apache"],
    "Cloudflare": [r"cloudflare", r"__cfduid", r"cf-ray"],
    "Google Analytics": [r"google-analytics", r"ga\("],
    "Hotjar": [r"hotjar", r"Hotjar"],
}

def fingerprint_tech(url: str) -> Dict:
    result = {"url": url, "technologies": [], "raw_headers": {}}
    try:
        resp = session.get(url, timeout=15, allow_redirects=True)
        result["raw_headers"] = dict(resp.headers)
        combined = resp.text.lower() + str(resp.headers).lower()
        for tech, patterns in TECH_SIGNATURES.items():
            for pat in patterns:
                if re.search(pat, combined, re.IGNORECASE):
                    result["technologies"].append(tech)
                    break
        server = resp.headers.get("Server", "")
        if server: result["technologies"].append(f"Server: {server}")
        x_powered = resp.headers.get("X-Powered-By", None)
        if x_powered: result["technologies"].append(f"X-Powered-By: {x_powered}")
        result["technologies"] = sorted(set(result["technologies"]))
    except Exception as e:
        result["error"] = str(e)
    return result

# ═════════════════════════════════════════════════════════════════════
# MODULE 7: SSL/TLS Certificate Analysis
# ═════════════════════════════════════════════════════════════════════
def ssl_analysis(domain: str, port: int = 443) -> Dict:
    result = {"host": domain, "port": port, "error": None}
    try:
        ctx = ssl.create_default_context()
        with socket.create_connection((domain, port), timeout=10) as sock:
            with ctx.wrap_socket(sock, server_hostname=domain) as ssock:
                cert = ssock.getpeercert()
                subject, issuer = {}, {}
                try:
                    subject = dict(cert.get("subject", []))
                    issuer = dict(cert.get("issuer", []))
                except (TypeError, ValueError):
                    pass # Handle malformed cert fields
                result.update({
                    "subject": subject,
                    "issuer": issuer,
                    "version": cert.get("version"),
                    "serial": cert.get("serialNumber"),
                    "not_before": cert.get("notBefore"),
                    "not_after": cert.get("notAfter"),
                    "san": cert.get("subjectAltName", []),
                    "cipher": ssock.cipher(),
                    "protocol": ssock.version(),
                })
                not_after = cert.get("notAfter", "")
                if not_after:
                    try:
                        expiry = datetime.strptime(not_after, "%b %d %H:%M:%S %Y %Z").replace(tzinfo=timezone.utc)
                        now = datetime.now(timezone.utc)
                        days_left = (expiry - now).days
                        result["days_remaining"] = days_left
                        result["expired"] = days_left < 0
                        result["expiring_soon"] = 0 <= days_left < 30
                    except ValueError:
                        pass
    except Exception as e:
        result["error"] = str(e)
    return result

# ═════════════════════════════════════════════════════════════════════
# MODULE 8: Email Harvesting
# ═════════════════════════════════════════════════════════════════════
EMAIL_REGEX = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"

def harvest_emails_from_url(url: str) -> List[str]:
    emails = set()
    try:
        resp = session.get(url, timeout=15)
        emails.update(re.findall(EMAIL_REGEX, resp.text))
    except Exception:
        pass
    return sorted(emails)

def harvest_emails_from_google(domain: str, max_pages: int = 3) -> List[str]:
    emails = set()
    try:
        for start in range(0, max_pages * 10, 10):
            url = f"https://www.google.com/search?q=%40{domain}&start={start}"
            resp = session.get(url, timeout=15)
            emails.update(re.findall(EMAIL_REGEX, resp.text))
            time.sleep(0.5)
    except Exception:
        pass
    return sorted(emails)

def harvest_emails_from_bing(domain: str, max_pages: int = 3) -> List[str]:
    emails = set()
    try:
        for first in range(1, max_pages * 10 + 1, 10):
            url = f"https://www.bing.com/search?q=%40{domain}&first={first}"
            resp = session.get(url, timeout=15)
            emails.update(re.findall(EMAIL_REGEX, resp.text))
            time.sleep(0.5)
    except Exception:
        pass
    return sorted(emails)

def email_harvest(domain: str, google: bool = True, bing: bool = True) -> Dict:
    all_emails = set()
    sources = {}
    try:
        w = whois.whois(domain)
        if w.emails:
            for e in w.emails:
                all_emails.add(e)
            sources["whois"] = list(w.emails)
    except Exception:
        pass
    for proto in ["http", "https"]:
        try:
            url = f"{proto}://{domain}"
            ems = harvest_emails_from_url(url)
            for e in ems: all_emails.add(e)
            sources[proto] = ems
        except Exception:
            pass
    if google:
        try:
            ems = harvest_emails_from_google(domain)
            sources["google"] = ems
            all_emails.update(ems)
        except Exception:
            pass
    if bing:
        try:
            ems = harvest_emails_from_bing(domain)
            sources["bing"] = ems
            all_emails.update(ems)
        except Exception:
            pass
    return {"domain": domain, "emails": sorted(all_emails), "sources": sources}

# ═════════════════════════════════════════════════════════════════════
# MODULE 9: Shodan / Shodan InternetDB
# ═════════════════════════════════════════════════════════════════════
SHODAN_API_KEY = os.environ.get("SHODAN_API_KEY", "")

def shodan_query(target: str) -> Dict:
    result = {"target": target, "source": "", "data": {}, "error": None}
    if SHODAN_API_KEY:
        try:
            import shodan  # type: ignore
            api = shodan.Shodan(SHODAN_API_KEY)
            ip = target if re.match(r"^\d+\.\d+\.\d+\.\d+$", target) else socket.gethostbyname(target)
            info = api.host(ip)
            result["source"] = "Shodan API"
            result["data"] = {
                "ip": info.get("ip_str"),
                "org": info.get("org", ""),
                "os": info.get("os", ""),
                "ports": info.get("ports", []),
                "hostnames": info.get("hostnames", []),
                "vulnerabilities": info.get("vulns", []),
            }
            return result
        except Exception as e:
            result["error"] = f"Shodan API failed: {e}"
    try:
        ip = target if re.match(r"^\d+\.\d+\.\d+\.\d+$", target) else socket.gethostbyname(target)
        resp = session.get(f"https://internetdb.shodan.io/{ip}", timeout=15)
        if resp.status_code == 200:
            result["source"] = "Shodan InternetDB"
            result["data"] = resp.json()
        else:
            result["error"] = f"InternetDB returned {resp.status_code}"
    except Exception as e:
        result["error"] = str(e)
    return result

# ═════════════════════════════════════════════════════════════════════
# MODULE 10: Web Crawling
# ═════════════════════════════════════════════════════════════════════
COMMON_PATHS = [
    "/", "/admin", "/login", "/wp-admin", "/administrator", "/panel",
    "/cpanel", "/backup", "/.env", "/.git/config", "/.gitignore",
    "/robots.txt", "/sitemap.xml", "/crossdomain.xml", "/phpinfo.php",
    "/info.php", "/test.php", "/config.php", "/config/", "/db/",
    "/database/", "/sql/", "/sqlite/", "/dump/", "/backup.sql",
    "/db.sql", "/dump.sql", "/README.md", "/CHANGELOG", "/composer.json",
    "/package.json", "/package-lock.json", "/yarn.lock", "/Dockerfile",
    "/docker-compose.yml", "/.htaccess", "/.htpasswd", "/.ssh/",
    "/.aws/credentials", "/.azure/", "/.kube/config", "/config.json",
    "/settings.json", "/secrets.json", "/credentials.json",
    "/swagger.json", "/api-docs", "/openapi.json", "/graphql",
    "/api/", "/api/v1/", "/api/v2/", "/api/health", "/api/status",
    "/console", "/management", "/monitor", "/logs", "/log/",
    "/error.log", "/access.log", "/debug.log", "/test/", "/tmp/",
    "/temp/", "/uploads/", "/upload/", "/files/", "/download/",
    "/backups/", "/.well-known/", "/.well-known/security.txt",
]

def web_crawl(domain: str, paths: Optional[List[str]] = None, follow_redirects: bool = True) -> Dict:
    base_paths = paths or COMMON_PATHS
    found = []
    def _check(path):
        for proto in ["https", "http"]:
            url = f"{proto}://{domain}{path}"
            try:
                resp = session.get(url, timeout=10, allow_redirects=follow_redirects)
                if resp.status_code in [200, 301, 302, 401, 403, 500]:
                    entry = {"url": url, "status": resp.status_code, "size": len(resp.content), "title": ""}
                    try:
                        soup = BeautifulSoup(resp.text, "html.parser")
                        t = soup.find("title")
                        if t: entry["title"] = t.get_text(strip=True)
                    except Exception:
                        pass
                    return entry
                return None
            except Exception:
                continue
        return None
    with concurrent.futures.ThreadPoolExecutor(max_workers=30) as ex:
        for f in concurrent.futures.as_completed({ex.submit(_check, p): p for p in base_paths}):
            try:
                r = f.result()
                if r: found.append(r)
            except Exception:
                pass
    found.sort(key=lambda x: x["url"])
    return {"domain": domain, "paths_checked": len(base_paths), "findings": found}

# ═════════════════════════════════════════════════════════════════════
# MODULE 11: Screenshot via Playwright
# ═════════════════════════════════════════════════════════════════════
def screenshot_subdomain(url: str, output_dir: Optional[Path] = None) -> Optional[str]:
    out = output_dir or SCREENSHOT_DIR
    try:
        from playwright.sync_api import sync_playwright  # type: ignore
        safe_name = re.sub(r"[^a-zA-Z0-9]", "_", url.split("//")[-1].split("/")[0])
        path = str(out / f"{safe_name}.png")
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page(viewport={"width": 1280, "height": 720})
            page.goto(url, timeout=30000, wait_until="domcontentloaded")
            page.screenshot(path=path, full_page=True)
            browser.close()
        return path
    except Exception as e:
        log_warn(f"Screenshot failed for {url}: {e}")
        return None

# ═════════════════════════════════════════════════════════════════════
# MODULE 12: CVE Correlation
# ═════════════════════════════════════════════════════════════════════
CVE_CACHE: Dict[str, List[Dict]] = {}

def cve_search(cpe: str) -> List[Dict]:
    if cpe in CVE_CACHE:
        return CVE_CACHE[cpe]
    results = []
    try:
        resp = session.get("https://services.nvd.nist.gov/rest/json/cves/2.0",
                           params={"cpeName": cpe, "resultsPerPage": 20},
                           timeout=20)
        if resp.status_code == 200:
            for vuln in resp.json().get("vulnerabilities", []):
                cve = vuln.get("cve", {})
                metrics = cve.get("metrics", {})
                base_score, severity = None, None
                for cvss_key in ["cvssMetricV31", "cvssMetricV30", "cvssMetricV2"]:
                    if cvss_key in metrics:
                        base_score = metrics[cvss_key][0]["cvssData"]["baseScore"]
                        severity = metrics[cvss_key][0]["cvssData"]["baseSeverity"]
                        break
                results.append({
                    "id": cve.get("id"),
                    "description": cve.get("descriptions", [{}])[0].get("value", ""),
                    "score": base_score,
                    "severity": severity,
                    "published": cve.get("published"),
                    "matched_cpe": cpe,
                })
        elif resp.status_code == 403:
            log_warn("NVD API rate limited")
    except Exception as e:
        log_warn(f"CVE search error: {e}")
    CVE_CACHE[cpe] = results
    return results

def _extract_version(text: str) -> Optional[str]:
    match = re.search(r"(?<![a-zA-Z])v?(\d+(?:\.\d+){0,3}(?:[-+][0-9A-Za-z_.-]+)?)", text)
    return match.group(1) if match else None

def _versioned_cpe_for_technology(technology: str) -> Optional[Dict[str, str]]:
    tech_to_cpe = {
        "nginx": ("nginx", "nginx"),
        "apache": ("apache", "http_server"),
        "wordpress": ("wordpress", "wordpress"),
        "drupal": ("drupal", "drupal"),
        "joomla": ("joomla", "joomla"),
        "laravel": ("laravel", "laravel"),
        "django": ("djangoproject", "django"),
        "flask": ("palletsprojects", "flask"),
        "jquery": ("jquery", "jquery"),
        "react": ("facebook", "react"),
        "vue.js": ("vuejs", "vue"),
        "vue": ("vuejs", "vue"),
        "angular": ("angular", "angular"),
        "bootstrap": ("getbootstrap", "bootstrap"),
        "express": ("expressjs", "express"),
        "asp.net": ("microsoft", "asp.net"),
        "ruby on rails": ("rubyonrails", "rails"),
        "rails": ("rubyonrails", "rails"),
    }
    raw = technology.strip()
    base = raw.split(":", 1)[1].strip() if ":" in raw else raw
    lowered = base.lower()
    version = _extract_version(base)
    if not version:
        return None
    key = None
    for candidate in sorted(tech_to_cpe, key=len, reverse=True):
        if candidate in lowered:
            key = candidate
            break
    if not key:
        return None
    vendor, product = tech_to_cpe[key]
    return {
        "technology": base,
        "version": version,
        "cpe": f"cpe:2.3:a:{vendor}:{product}:{version}:*:*:*:*:*:*:*"
    }

def cve_correlation(tech_list: List[str]) -> Dict:
    result = {"technologies_checked": [], "skipped": [], "findings": []}
    seen_cpes = set()
    for tech in tech_list:
        cpe_info = _versioned_cpe_for_technology(tech)
        if not cpe_info:
            result["skipped"].append({"technology": tech, "reason": "no supported version-specific CPE"})
            continue
        cpe = cpe_info["cpe"]
        if cpe in seen_cpes:
            continue
        seen_cpes.add(cpe)
        result["technologies_checked"].append(cpe_info)
        cves = cve_search(cpe)
        for cve in cves:
            cve["technology"] = cpe_info["technology"]
            cve["version"] = cpe_info["version"]
        result["findings"].extend(cves)
    return result

# ═════════════════════════════════════════════════════════════════════
# PDF REPORT GENERATION
# ═════════════════════════════════════════════════════════════════════
def generate_pdf_report(data: Dict, filepath: str) -> str:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
    doc = SimpleDocTemplate(filepath, pagesize=A4,
                            rightMargin=15*mm, leftMargin=15*mm,
                            topMargin=15*mm, bottomMargin=15*mm)
    styles = getSampleStyleSheet()
    story = []
    ts = ParagraphStyle("Title2", parent=styles["Title"], fontSize=22, spaceAfter=12)
    cs = ParagraphStyle("Code", parent=styles["Normal"], fontName="Courier", fontSize=8, leading=10)

    story.append(Paragraph("ReconSuite v2.0 — Security Assessment Report", ts))
    story.append(Paragraph(f"<b>Target:</b> {data.get('target', 'N/A')}", styles["Normal"]))
    story.append(Paragraph(f"<b>Scan Date:</b> {data.get('date', '')}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("1. Executive Summary", styles["Heading1"]))
    total = 0
    sev_count = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for s in data.get("sections", []):
        for f in s.get("findings", []):
            total += 1
            sev = f.get("severity", "info").lower()
            if sev in sev_count: sev_count[sev] += 1
    story.append(Paragraph(f"Total issues: {total}", styles["Normal"]))
    story.append(Paragraph(f"Critical: {sev_count['critical']} | High: {sev_count['high']} | "
                           f"Medium: {sev_count['medium']} | Low: {sev_count['low']} | Info: {sev_count['info']}",
                           styles["Normal"]))
    story.append(Spacer(1, 12))

    for section in data.get("sections", []):
        story.append(Paragraph(f"2. {section['title']}", styles["Heading1"]))
        for finding in section.get("findings", []):
            sev = finding.get("severity", "info").upper()
            story.append(Paragraph(f"<b>[{sev}]</b> {finding.get('title', '')}", styles["Heading2"]))
            story.append(Paragraph(finding.get("description", ""), styles["Normal"]))
            if finding.get("recommendation"):
                story.append(Paragraph(f"<b>Recommendation:</b> {finding['recommendation']}", styles["Normal"]))
            if finding.get("details"):
                story.append(Paragraph(f"<b>Details:</b> {finding['details']}", cs))
            story.append(Spacer(1, 8))

    story.append(Spacer(1, 20))
    story.append(Paragraph(DISCLAIMER.replace("---\n", ""), cs))
    doc.build(story)
    return filepath

# ═════════════════════════════════════════════════════════════════════
# SCAN ORCHESTRATOR
# ═════════════════════════════════════════════════════════════════════
def full_scan(domain: str, modules: Dict[str, bool], progress_callback=None) -> Dict:
    import ipaddress
    start = time.time()
    results = {"target": domain, "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
               "scan_duration": 0, "modules": {}}
    threads = {}

    is_ip = False
    try:
        ipaddress.ip_address(domain)
        is_ip = True
    except ValueError:
        pass

    # Disable modules that don't work on IPs
    if is_ip:
        modules["subdomains"] = modules["subdomain_brute"] = modules["subdomain_passive"] = False

    # --- Define module-specific progress handlers ---
    def create_sub_progress_handler(module_name, weight):
        def handler(completed, total):
            if progress_callback:
                # This is a simplified weighted progress. A more complex system
                # could be built, but this gives a good sense of movement.
                # We report the main module name, but the progress is for the sub-task.
                progress_callback(module_name, completed, total)
        return handler

    if modules.get("whois", True):
        threads["whois"] = threading.Thread(target=lambda: results["modules"].update(
            {"whois": whois_lookup(domain)}))
    if modules.get("dns", True):
        threads["dns"] = threading.Thread(target=lambda: results["modules"].update(
            {"dns": dns_enum(domain)}))
    if modules.get("subdomains", True):
        subdomain_progress = create_sub_progress_handler("subdomains", 4)
        threads["subdomains"] = threading.Thread(target=lambda: results["modules"].update(
            {"subdomains": subdomain_enum(domain, modules.get("subdomain_brute", True),
                                          modules.get("subdomain_passive", True),
                                          progress_callback=subdomain_progress)}))
    if modules.get("ports", True):
        port_progress = create_sub_progress_handler("ports", 5)
        threads["ports"] = threading.Thread(target=lambda: results["modules"].update(
            {"ports": port_scan(domain, progress_callback=port_progress)}))
    if modules.get("headers", True):
        threads["headers"] = threading.Thread(target=lambda: results["modules"].update(
            {"headers": check_http_headers(f"https://{domain}")}))
    if modules.get("fingerprint", True):
        threads["fingerprint"] = threading.Thread(target=lambda: results["modules"].update(
            {"tech_fingerprint": fingerprint_tech(f"https://{domain}")}))
    if modules.get("ssl", True):
        threads["ssl"] = threading.Thread(target=lambda: results["modules"].update(
            {"ssl": ssl_analysis(domain)}))
    if modules.get("emails", True):
        threads["emails"] = threading.Thread(target=lambda: results["modules"].update(
            {"emails": email_harvest(domain, modules.get("email_google", True),
                                     modules.get("email_bing", True))}))
    if modules.get("shodan", True):
        threads["shodan"] = threading.Thread(target=lambda: results["modules"].update(
            {"shodan": shodan_query(domain)}))
    if modules.get("crawl", True):
        threads["crawl"] = threading.Thread(target=lambda: results["modules"].update(
            {"web_crawl": web_crawl(domain)}))

    total_modules = len(threads)
    completed_modules = [0]
    lock = threading.Lock()

    def _run(name, t):
        t.start(); t.join()
        with lock:
            completed_modules[0] += 1
            if progress_callback:
                # When a main module thread finishes, report its completion
                # This is different from the sub-progress reported within the thread
                # For simplicity, we'll just use the module name and the overall count.
                # The UI will see progress updates for "ports" (sub-progress) and then
                # a final update for "ports" when the whole module is done.
                progress_callback(name, completed_modules[0], total_modules)

    runners = []
    for name, t in threads.items():
        rt = threading.Thread(target=_run, args=(name, t))
        rt.start(); runners.append(rt)
    for r in runners:
        r.join()
    results["scan_duration"] = round(time.time() - start, 2)

    if modules.get("cve", True):
        tech_list = results["modules"].get("tech_fingerprint", {}).get("technologies", [])
        results["modules"]["cve"] = cve_correlation(tech_list)
    if modules.get("screenshots", False):
        subdomains = results["modules"].get("subdomains", {}).get("all", [])
        ss = []
        for sd in subdomains[:10]:
            for proto in ["https", "http"]:
                p = screenshot_subdomain(f"{proto}://{sd}")
                if p:
                    ss.append({"subdomain": sd, "screenshot": p})
                    break
        results["modules"]["screenshots"] = ss
    return results

def scan_to_report_sections(scan_result: Dict) -> List[Dict]:
    sections = []
    for mod_name, mod_data in scan_result.get("modules", {}).items():
        findings = []
        if mod_name == "whois" and mod_data:
            if mod_data.get("error"):
                findings.append({"severity": "info", "title": "WHOIS Lookup Failed",
                                 "description": str(mod_data["error"]),
                                 "recommendation": "Check domain/network"})
            else:
                findings.append({"severity": "info", "title": "WHOIS Data",
                                 "description": f"Registrar: {mod_data.get('registrar', 'N/A')}",
                                 "details": f"Creation: {mod_data.get('creation_date')}\nExpiry: {mod_data.get('expiration_date')}\nNS: {', '.join(mod_data.get('name_servers', [])[:5])}",
                                 "recommendation": "Enable WHOIS privacy if needed"})
            sections.append({"title": "WHOIS Information", "findings": findings, "raw": mod_data})
        elif mod_name == "subdomains" and mod_data:
            all_sd = mod_data.get("all", [])
            findings.append({"severity": "info" if len(all_sd) < 10 else "medium",
                             "title": f"Subdomains: {len(all_sd)}",
                             "description": f"Found {len(all_sd)} subdomains",
                             "details": "\n".join(all_sd[:50]) if all_sd else "None",
                             "recommendation": "Review discovered subdomains"})
            if len(all_sd) > 20:
                findings.append({"severity": "medium", "title": "Large Subdomain Footprint",
                                 "description": f"{len(all_sd)} subdomains increases attack surface",
                                 "recommendation": "Audit all subdomains"})
            sections.append({"title": "Subdomain Enumeration", "findings": findings, "raw": mod_data})
        elif mod_name == "ports" and mod_data:
            ports = mod_data.get("open_ports", [])
            findings.append({"severity": "high" if len(ports) > 20 else "medium",
                             "title": f"Open Ports: {len(ports)}",
                             "description": f"Scanned {mod_data.get('total_scanned', 0)} ports, {len(ports)} open",
                             "details": ", ".join(str(p) for p in ports),
                             "recommendation": "Close unnecessary ports"})
            sensitive = {21: "FTP", 23: "Telnet", 25: "SMTP", 135: "MSRPC", 139: "NetBIOS",
                         445: "SMB", 1433: "MSSQL", 3306: "MySQL", 3389: "RDP", 5900: "VNC",
                         6379: "Redis", 27017: "MongoDB", 5432: "PostgreSQL"}
            for p in ports:
                if p in sensitive:
                    findings.append({"severity": "high", "title": f"Sensitive Port {p} ({sensitive[p]})",
                                     "description": f"Port {p} ({sensitive[p]}) exposed",
                                     "recommendation": f"Restrict port {p}"})
            sections.append({"title": "Port Scanning", "findings": findings, "raw": mod_data})
        elif mod_name == "headers" and mod_data:
            score = mod_data.get("score", 50)
            sev = "high" if score < 40 else "medium" if score < 70 else "low"
            findings.append({"severity": sev, "title": f"Security Headers: {score}/100",
                             "description": "HTTP security headers audit",
                             "details": "\n".join(f"{i['header']}: {i['description']}" for i in mod_data.get("issues", [])),
                             "recommendation": "Implement missing security headers"})
            sections.append({"title": "HTTP Security Headers", "findings": findings, "raw": mod_data})
        elif mod_name == "tech_fingerprint" and mod_data:
            techs = mod_data.get("technologies", [])
            findings.append({"severity": "info", "title": f"Technologies: {len(techs)}",
                             "description": "\n".join(techs),
                             "recommendation": "Keep software updated"})
            sections.append({"title": "Tech Stack", "findings": findings, "raw": mod_data})
        elif mod_name == "ssl" and mod_data:
            if mod_data.get("error"):
                findings.append({"severity": "high", "title": "SSL Error",
                                 "description": str(mod_data["error"]),
                                 "recommendation": "Check SSL config"})
            else:
                if mod_data.get("expired"):
                    findings.append({"severity": "critical", "title": "SSL Certificate Expired",
                                     "recommendation": "Renew immediately"})
                elif mod_data.get("expiring_soon"):
                    findings.append({"severity": "high", "title": "SSL Expiring Soon",
                                     "description": f"{mod_data['days_remaining']} days remaining",
                                     "recommendation": "Renew before expiry"})
                findings.append({"severity": "info", "title": "SSL Details",
                                 "description": f"Issuer: {mod_data.get('issuer')}\nProtocol: {mod_data.get('protocol')}\nExpires: {mod_data.get('not_after')}"})
            sections.append({"title": "SSL/TLS", "findings": findings, "raw": mod_data})
        elif mod_name == "emails" and mod_data:
            emails = mod_data.get("emails", [])
            findings.append({"severity": "high" if len(emails) > 10 else "medium",
                             "title": f"Emails: {len(emails)}",
                             "description": f"Found {len(emails)} email addresses",
                             "details": "\n".join(emails),
                             "recommendation": "Reduce email exposure"})
            sections.append({"title": "Email Harvesting", "findings": findings, "raw": mod_data})
        elif mod_name == "shodan" and mod_data:
            if mod_data.get("data"):
                cves = mod_data["data"].get("vulnerabilities", [])
                findings.append({"severity": "critical" if cves else "info",
                                 "title": f"Shodan/{mod_data.get('source', 'InternetDB')}",
                                 "description": f"Ports: {len(mod_data['data'].get('ports', []))}, CVEs: {len(cves)}",
                                 "details": f"CVEs: {', '.join(cves)}" if cves else "No known CVEs",
                                 "recommendation": "Patch known CVEs"})
                sections.append({"title": "Shodan Intelligence", "findings": findings, "raw": mod_data})
        elif mod_name == "web_crawl" and mod_data:
            interesting = [f for f in mod_data.get("findings", []) if f.get("status") in [200, 401, 403]]
            findings.append({"severity": "medium" if len(interesting) > 3 else "low",
                             "title": f"Interesting Paths: {len(interesting)}",
                             "description": f"Crawled {mod_data.get('paths_checked')} paths",
                             "details": "\n".join(f"{f['url']} [{f['status']}] {f.get('title', '')}" for f in interesting[:20]),
                             "recommendation": "Review interesting paths"})
            sections.append({"title": "Web Crawling", "findings": findings, "raw": mod_data})
        elif mod_name == "cve" and mod_data:
            for cve in mod_data.get("findings", []):
                sev = (cve.get("severity") or "medium").lower()
                findings.append({"severity": sev if sev in ["critical","high","medium","low"] else "medium",
                                 "title": f"{cve.get('id', 'CVE')} (CVSS: {cve.get('score', 'N/A')})",
                                 "description": (cve.get("description") or "")[:300],
                                 "recommendation": f"Patch {cve.get('id', 'vulnerability')}"})
            sections.append({"title": "CVE Correlation", "findings": findings, "raw": mod_data})
    return sections

def export_reports(scan_result: Dict, base_name: str, formats: List[str]) -> Dict[str, str]:
    paths = {}
    if "json" in formats:
        paths["json"] = save_json(scan_result, base_name)
    if "md" in formats or "markdown" in formats:
        md = f"# ReconSuite v2.0 Report — {scan_result['target']}\n\n"
        md += f"**Scan Date:** {scan_result['date']}  \n**Duration:** {scan_result['scan_duration']}s\n\n"
        for sec in scan_to_report_sections(scan_result):
            md += f"## {sec['title']}\n\n"
            for f in sec.get("findings", []):
                md += f"### [{f.get('severity','info').upper()}] {f['title']}\n{f['description']}\n\n"
                if f.get("recommendation"):
                    md += f"**Recommendation:** {f['recommendation']}\n\n"
            if sec.get("raw"):
                md += "```json\n" + json.dumps(sec["raw"], indent=2, default=str)[:2000] + "\n```\n\n"
        md += DISCLAIMER
        paths["md"] = save_markdown(md, base_name)
    if "pdf" in formats:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        pdf_path = str(OUTPUT_DIR / f"{base_name}_{ts}.pdf")
        sections = scan_to_report_sections(scan_result)
        generate_pdf_report({"target": scan_result["target"], "date": scan_result["date"],
                             "sections": sections}, pdf_path)
        paths["pdf"] = pdf_path
    return paths

# ═════════════════════════════════════════════════════════════════════
# CLI ARGUMENT PARSER
# ═════════════════════════════════════════════════════════════════════
def parse_args():
    parser = argparse.ArgumentParser(
        description="ReconSuite v2.0 — Full-Spectrum Reconnaissance Toolkit",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  recon_cli.py example.com
  recon_cli.py example.com --only ports,headers,ssl
  recon_cli.py example.com --skip emails --output json,md,pdf
  recon_cli.py --targets targets.txt --proxy socks5://127.0.0.1:9050
  recon_cli.py example.com --screenshots --cve""")
    parser.add_argument("target", nargs="?", help="Target domain or IP")
    parser.add_argument("--targets", help="Path to targets.txt file")
    parser.add_argument("--only", help="Comma-separated modules to run")
    parser.add_argument("--skip", help="Comma-separated modules to skip", default="screenshots")
    parser.add_argument("--output", help="Output formats: json,md,pdf", default="json,md")
    parser.add_argument("--proxy", help="Proxy URL (HTTP/HTTPS/SOCKS5)")
    parser.add_argument("--tor", action="store_true", help="Route through Tor SOCKS5")
    parser.add_argument("--screenshots", action="store_true", help="Capture screenshots")
    parser.add_argument("--cve", action="store_true", help="CVE correlation")
    parser.add_argument("--threads", type=int, default=50, help="Max threads")
    return parser.parse_args()

def resolve_modules(args) -> Dict[str, bool]:
    all_modules = ["whois", "dns", "subdomains", "subdomain_brute", "subdomain_passive",
                   "ports", "headers", "fingerprint", "ssl", "emails", "email_google",
                   "email_bing", "shodan", "crawl", "cve", "screenshots"]
    defaults = {m: True for m in all_modules}
    defaults["screenshots"] = False
    defaults["subdomain_brute"] = True
    defaults["subdomain_passive"] = True
    defaults["email_google"] = True
    defaults["email_bing"] = True
    defaults["cve"] = False
    if args.only:
        only_set = set(args.only.lower().split(","))
        for m in all_modules:
            defaults[m] = m in only_set
        return defaults
    if args.skip:
        skip_set = set(args.skip.lower().split(","))
        for m in all_modules:
            if m in skip_set:
                defaults[m] = False
    if args.screenshots:
        defaults["screenshots"] = True
    if args.cve:
        defaults["cve"] = True
    return defaults

# ═════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ═════════════════════════════════════════════════════════════════════
def main():
    args = parse_args()
    configure_proxy(args.proxy, args.tor)
    targets = []

    if args.targets:
        try:
            with open(args.targets, "r") as f:
                targets = [line.strip() for line in f if line.strip() and not line.startswith("#")]
        except FileNotFoundError:
            log_err(f"Targets file not found: {args.targets}")
            sys.exit(1)
    elif args.target:
        targets = [args.target]
    else:
        log_err("No target specified. Provide a domain or use --targets")
        sys.exit(1)

    output_formats = [f.strip().lower() for f in args.output.split(",")]
    modules = resolve_modules(args)

    log_info(f"Modules enabled: {', '.join(k for k, v in modules.items() if v)}")
    log_info(f"Output formats: {', '.join(output_formats)}")

    for target in targets:
        print(f"\n{'='*60}")
        log_info(f"Scanning target: {target}")
        print(f"{'='*60}")
        log_info("Running all modules in parallel...")
        results = full_scan(target, modules)
        duration = results["scan_duration"]
        log_ok(f"Scan completed in {duration}s")

        # Print summary
        for mod, data in results["modules"].items():
            if isinstance(data, dict):
                if mod == "whois":
                    if data.get("registrar"):
                        log_ok(f"[WHOIS] Registrar: {data['registrar']}")
                elif mod == "subdomains":
                    log_ok(f"[Subdomains] {len(data.get('all',[]))} found ({len(data.get('bruteforce',[]))} brute, {len(data.get('passive',[]))} passive)")
                elif mod == "ports":
                    log_ok(f"[Ports] {len(data.get('open_ports',[]))} open")
                elif mod == "headers":
                    log_ok(f"[Headers] Score: {data.get('score', 'N/A')}/100")
                elif mod == "ssl":
                    if data.get("expired"):
                        log_err("[SSL] CERTIFICATE EXPIRED!")
                elif mod == "emails":
                    log_ok(f"[Emails] {len(data.get('emails',[]))} found")
                elif mod == "cve":
                    log_ok(f"[CVE] {len(data.get('findings',[]))} CVEs matched")
                elif mod == "web_crawl":
                    log_ok(f"[Crawl] {len(data.get('findings',[]))} interesting paths")
                elif mod == "shodan" and data.get("data"):
                    log_ok(f"[Shodan] {len(data['data'].get('ports',[]))} ports, {len(data['data'].get('vulnerabilities',[]))} vulns")

        safe_name = re.sub(r"[^a-zA-Z0-9]", "_", target)
        exported = export_reports(results, safe_name, output_formats)
        for fmt, path in exported.items():
            log_ok(f"Report saved: {path}")

        log_info(f"Scan of {target} complete.")

    print(f"\n{Fore.GREEN}All scans complete. Reports saved to {OUTPUT_DIR}/{Style.RESET_ALL}")
    print(f"{Fore.MAGENTA}{DISCLAIMER}{Style.RESET_ALL}")

if __name__ == "__main__":
    main()
